version: '3'
services: 
  #sqlserver:
   # image: mcr.microsoft.com/mssql/server:2019-latest
   # restart: always
   # ports:
   #   - 1433:1433
   # environment:
   #  MSSQL_SA_PASSWORD: example@123
   #  MSSQL_PID: EXPRESS
   #  ACCEPT_EULA: Y
   # networks: 
   #   - internal-container-network
   # volumes:
   #   - sqlserver-data:/var/opt/mssql

  db:
    image: mariadb:latest
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: example
    networks: 
      - internal-container-network
    volumes:
      - mariadb-data:/var/lib/mysql

  comservice:
    image: comservice:v91
    restart: always
    networks: 
     - internal-container-network 
  
  hospital:
    image: hospital_app:v5
    networks:
      - internal-container-network
    ports:
      - 8103:80
    depends_on:
      - db 
  
  training:
    image: training:v16
    networks:
      - internal-container-network
    depends_on:
      - db 
<<<<<<< HEAD
      
=======
 
>>>>>>> 3b5b10b436884e7b584c68c7b07c601800c6b934
  reports:
    image: reports:v25
    networks:
      - internal-container-network
    volumes:
      - pdf-data:/App/assets/pdf
    depends_on:
      - db

  onlinevalve_md:
    image: inventory_md:v26
    networks:
     - internal-container-network
    volumes:
     - sqldata:/root/.aspnet/DataProtection-Keys
    ports:
     - 8045:80
    depends_on: 
     - db

  tracPersonal:
    image: sql_app:v96
    ports:
     - 8086:80
    networks: 
     - internal-container-network
    volumes:
     - sqldata:/root/.aspnet/DataProtection-Keys
     - pdf-data:/App/assets/pdf
    depends_on: 
     - db
     - comservice
     - onlinevalve_md

volumes:
 mariadb-data:
 sqldata:
 pdf-data:
networks:
 internal-container-network:
  driver: bridge
